import type { CandidateProfile } from "./candidateProfiles.types";

export const candidateProfilesPartOne: Record<string, CandidateProfile> = {
  "1": {
    bio: "Passionate React developer with 5+ years of experience building scalable web applications. Loves clean code, intuitive interfaces, and strong collaboration across product teams.",
    candidateId: "1",
    documents: { resumeName: "Hammed-Adeyanju-Resume.pdf", resumeSize: 2516582, resumeUrl: "#" },
    emailAddress: "hammed.adeyanju@gmail.com",
    experiences: [
      {
        companyName: "Bubbl HQ",
        currentlyWorking: false,
        description:
          "Led frontend delivery across dashboard and growth surfaces, improving product consistency and performance while partnering closely with design and product teams.",
        endDate: "2024-03-01",
        jobTitle: "Senior Frontend Engineer",
        startDate: "2020-01-01",
      },
      {
        companyName: "Studio Layer",
        currentlyWorking: false,
        description:
          "Built reusable React components and polished user journeys for customer-facing experiences with a strong focus on accessibility and maintainability.",
        endDate: "2019-12-01",
        jobTitle: "Frontend Engineer",
        startDate: "2017-06-01",
      },
    ],
    firstName: "Hammed",
    jobTitle: "Senior Frontend Engineer",
    lastName: "Adeyanju",
    linkedinProfile: "https://linkedin.com/in/hammed-adeyanju",
    location: "Lagos, Nigeria",
    name: "Hammed Adeyanju",
    phone: "+234 801 234 5678",
    portfolioWebsite: "https://hammed.dev",
    profilePicture: "",
    resumeName: "Hammed-Adeyanju-Resume.pdf",
    resumeSize: 2516582,
    resumeUrl: "#",
  },
  "2": {
    bio: "Frontend engineer focused on accessible interfaces, performance, and thoughtful product polish across modern web stacks.",
    candidateId: "2",
    documents: { resumeName: "Esther-Okon-Resume.pdf", resumeSize: 2097152, resumeUrl: "#" },
    emailAddress: "esther.okon@gmail.com",
    experiences: [
      {
        companyName: "Nexa Labs",
        currentlyWorking: true,
        description:
          "Owns key parts of the customer dashboard, building accessible UI patterns and improving rendering performance on high-traffic product surfaces.",
        endDate: "",
        jobTitle: "Senior Frontend Engineer",
        startDate: "2022-02-01",
      },
      {
        companyName: "Pixel Foundry",
        currentlyWorking: false,
        description:
          "Worked across web design systems and implementation details to help teams ship consistent features faster.",
        endDate: "2022-01-01",
        jobTitle: "Frontend Engineer",
        startDate: "2019-04-01",
      },
    ],
    firstName: "Esther",
    jobTitle: "Senior Frontend Engineer",
    lastName: "Okon",
    linkedinProfile: "https://linkedin.com/in/esther-okon",
    location: "Lagos, Nigeria",
    name: "Esther Okon",
    phone: "+234 802 345 6789",
    portfolioWebsite: "https://estherokon.dev",
    profilePicture: "",
    resumeName: "Esther-Okon-Resume.pdf",
    resumeSize: 2097152,
    resumeUrl: "#",
  },
  "3": {
    bio: "Growth-minded marketing leader with strong storytelling, campaign planning, and digital channel optimization skills.",
    candidateId: "3",
    documents: { resumeName: "Tolu-Johnson-Resume.pdf", resumeSize: 1887437, resumeUrl: "#" },
    emailAddress: "tolu.johnson@gmail.com",
    experiences: [
      {
        companyName: "Scale Circle",
        currentlyWorking: true,
        description:
          "Leads acquisition strategy, campaign planning, and lifecycle messaging across multiple growth channels with a strong analytics lens.",
        endDate: "",
        jobTitle: "Marketing Lead",
        startDate: "2021-05-01",
      },
      {
        companyName: "Bright Reach",
        currentlyWorking: false,
        description:
          "Managed integrated campaigns and performance reporting for digital launches and content-driven acquisition programs.",
        endDate: "2021-04-01",
        jobTitle: "Growth Marketing Specialist",
        startDate: "2018-08-01",
      },
    ],
    firstName: "Tolu",
    jobTitle: "Marketing Lead",
    lastName: "Johnson",
    linkedinProfile: "https://linkedin.com/in/tolu-johnson",
    location: "Remote",
    name: "Tolu Johnson",
    phone: "+234 803 456 7890",
    portfolioWebsite: "https://tolujohnson.me",
    profilePicture: "",
    resumeName: "Tolu-Johnson-Resume.pdf",
    resumeSize: 1887437,
    resumeUrl: "#",
  },
  "4": {
    bio: "Product designer experienced in building elegant design systems, user flows, and visually consistent digital products.",
    candidateId: "4",
    documents: { resumeName: "Femilare-Olatunji-Resume.pdf", resumeSize: 2149580, resumeUrl: "#" },
    emailAddress: "femilare.olatunji@gmail.com",
    experiences: [
      {
        companyName: "Palette Labs",
        currentlyWorking: true,
        description:
          "Designs end-to-end experiences, design systems, and interaction patterns for product teams shipping across web and mobile.",
        endDate: "",
        jobTitle: "Product Designer",
        startDate: "2022-06-01",
      },
      {
        companyName: "North Studio",
        currentlyWorking: false,
        description:
          "Created polished product UI, contributed to design systems, and partnered with engineers to turn concepts into shipped experiences.",
        endDate: "2022-05-01",
        jobTitle: "UI Designer",
        startDate: "2019-02-01",
      },
    ],
    firstName: "Femilare",
    jobTitle: "Product Designer",
    lastName: "Olatunji",
    linkedinProfile: "https://linkedin.com/in/femilare-olatunji",
    location: "Lagos, Nigeria",
    name: "Femilare Olatunji",
    phone: "+234 804 567 8901",
    portfolioWebsite: "https://femilare.design",
    profilePicture: "",
    resumeName: "Femilare-Olatunji-Resume.pdf",
    resumeSize: 2149580,
    resumeUrl: "#",
  },
  "5": {
    bio: "React developer who enjoys shipping thoughtful features, improving maintainability, and collaborating closely with product teams.",
    candidateId: "5",
    documents: { resumeName: "Amara-Nwosu-Resume.pdf", resumeSize: 1808793, resumeUrl: "#" },
    emailAddress: "amara.nwosu@gmail.com",
    experiences: [
      {
        companyName: "Vertex Stack",
        currentlyWorking: true,
        description:
          "Builds frontend features with React and TypeScript, supporting cross-functional teams with maintainable code and improved delivery speed.",
        endDate: "",
        jobTitle: "Frontend Engineer",
        startDate: "2023-01-01",
      },
      {
        companyName: "Code Avenue",
        currentlyWorking: false,
        description:
          "Implemented customer-facing interfaces and collaborated on component architecture for a growing SaaS platform.",
        endDate: "2022-12-01",
        jobTitle: "Frontend Developer",
        startDate: "2020-03-01",
      },
    ],
    firstName: "Amara",
    jobTitle: "Frontend Engineer",
    lastName: "Nwosu",
    linkedinProfile: "https://linkedin.com/in/amara-nwosu",
    location: "Abuja, Nigeria",
    name: "Amara Nwosu",
    phone: "+234 805 678 9012",
    portfolioWebsite: "https://amara.dev",
    profilePicture: "",
    resumeName: "Amara-Nwosu-Resume.pdf",
    resumeSize: 1808793,
    resumeUrl: "#",
  },
};
