import type { CandidateProfile } from "./candidateProfiles.types";

export const candidateProfilesPartTwo: Record<string, CandidateProfile> = {
  "6": {
    bio: "Backend and platform-focused engineer with solid API design, cloud deployment, and systems thinking experience.",
    candidateId: "6",
    documents: { resumeName: "David-Musa-Resume.pdf", resumeSize: 2306867, resumeUrl: "#" },
    emailAddress: "david.musa@gmail.com",
    experiences: [
      {
        companyName: "Cloudforge",
        currentlyWorking: true,
        description:
          "Leads backend services and infrastructure improvements around API reliability, deployment workflows, and performance visibility.",
        endDate: "",
        jobTitle: "Backend Engineer",
        startDate: "2021-11-01",
      },
      {
        companyName: "Scale Node",
        currentlyWorking: false,
        description:
          "Built and maintained APIs, background jobs, and service integrations for business-critical internal systems.",
        endDate: "2021-10-01",
        jobTitle: "Software Engineer",
        startDate: "2018-05-01",
      },
    ],
    firstName: "David",
    jobTitle: "Backend Engineer",
    lastName: "Musa",
    linkedinProfile: "https://linkedin.com/in/david-musa",
    location: "Remote",
    name: "David Musa",
    phone: "+234 806 789 0123",
    portfolioWebsite: "https://davidmusa.dev",
    profilePicture: "",
    resumeName: "David-Musa-Resume.pdf",
    resumeSize: 2306867,
    resumeUrl: "#",
  },
  "7": {
    bio: "Content and acquisition marketer who blends analytics with creativity to turn product messaging into measurable results.",
    candidateId: "7",
    documents: { resumeName: "Zainab-Ibrahim-Resume.pdf", resumeSize: 1945600, resumeUrl: "#" },
    emailAddress: "zainab.ibrahim@gmail.com",
    experiences: [
      {
        companyName: "Launch Lane",
        currentlyWorking: true,
        description:
          "Runs content and acquisition programs with a strong performance mindset, balancing experimentation with clear reporting.",
        endDate: "",
        jobTitle: "Marketing Specialist",
        startDate: "2022-04-01",
      },
      {
        companyName: "Signal House",
        currentlyWorking: false,
        description:
          "Executed demand generation campaigns, editorial calendars, and conversion-focused product messaging.",
        endDate: "2022-03-01",
        jobTitle: "Content Marketer",
        startDate: "2019-01-01",
      },
    ],
    firstName: "Zainab",
    jobTitle: "Marketing Specialist",
    lastName: "Ibrahim",
    linkedinProfile: "https://linkedin.com/in/zainab-ibrahim",
    location: "Lagos, Nigeria",
    name: "Zainab Ibrahim",
    phone: "+234 807 890 1234",
    portfolioWebsite: "https://zainabibrahim.me",
    profilePicture: "",
    resumeName: "Zainab-Ibrahim-Resume.pdf",
    resumeSize: 1945600,
    resumeUrl: "#",
  },
  "8": {
    bio: "UI designer with strong visual instincts, component thinking, and a sharp eye for interaction detail across mobile and web.",
    candidateId: "8",
    documents: { resumeName: "Mary-Ojo-Resume.pdf", resumeSize: 1769472, resumeUrl: "#" },
    emailAddress: "mary.ojo@gmail.com",
    experiences: [
      {
        companyName: "Canvas Works",
        currentlyWorking: true,
        description:
          "Designs modern product interfaces, collaborates on design systems, and refines interaction detail across responsive experiences.",
        endDate: "",
        jobTitle: "UI Designer",
        startDate: "2021-09-01",
      },
      {
        companyName: "Nova Creative",
        currentlyWorking: false,
        description:
          "Created visual systems and user interface assets for digital products spanning web experiences and internal platforms.",
        endDate: "2021-08-01",
        jobTitle: "Visual Designer",
        startDate: "2018-06-01",
      },
    ],
    firstName: "Mary",
    jobTitle: "UI Designer",
    lastName: "Ojo",
    linkedinProfile: "https://linkedin.com/in/mary-ojo",
    location: "Abuja, Nigeria",
    name: "Mary Ojo",
    phone: "+234 808 901 2345",
    portfolioWebsite: "https://maryojo.design",
    profilePicture: "",
    resumeName: "Mary-Ojo-Resume.pdf",
    resumeSize: 1769472,
    resumeUrl: "#",
  },
  "9": {
    bio: "Senior frontend engineer experienced with React, TypeScript, performance tuning, and cross-functional product development.",
    candidateId: "9",
    documents: { resumeName: "Kunle-Adebayo-Resume.pdf", resumeSize: 2211840, resumeUrl: "#" },
    emailAddress: "kunle.adebayo@gmail.com",
    experiences: [
      {
        companyName: "Atlas Commerce",
        currentlyWorking: true,
        description:
          "Owns frontend architecture for key commerce flows with an emphasis on performance, maintainability, and thoughtful UX details.",
        endDate: "",
        jobTitle: "Senior Frontend Engineer",
        startDate: "2022-07-01",
      },
      {
        companyName: "Bright Loop",
        currentlyWorking: false,
        description:
          "Built TypeScript-based interfaces and reusable UI primitives while supporting rapid delivery across multiple product squads.",
        endDate: "2022-06-01",
        jobTitle: "Frontend Engineer",
        startDate: "2019-03-01",
      },
    ],
    firstName: "Kunle",
    jobTitle: "Senior Frontend Engineer",
    lastName: "Adebayo",
    linkedinProfile: "https://linkedin.com/in/kunle-adebayo",
    location: "Lagos, Nigeria",
    name: "Kunle Adebayo",
    phone: "+234 809 012 3456",
    portfolioWebsite: "https://kunle.dev",
    profilePicture: "",
    resumeName: "Kunle-Adebayo-Resume.pdf",
    resumeSize: 2211840,
    resumeUrl: "#",
  },
};
